server:
    port: 9191

spring:
    application:
        name: batch-demo
    batch:
        jdbc:
            initialize-schema: ALWAYS
        job:
            enabled: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: qwer!@34
        url: jdbc:mysql://localhost:3306/batch
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus